plugins:
  images_guardian_enabled:
    default: true
  images_guardian_site_digest_logo_url:
    default: ""
  images_guardian_site_large_icon_url:
    default: ""
  images_guardian_site_manifest_icon_url:
    default: ""
  images_guardian_site_apple_touch_icon_url:
    default: ""
  images_guardian_site_x_summary_large_image_url:
    default: ""
  images_guardian_site_opengraph_image_url:
    default: ""
  images_guardian_site_push_notifications_icon_url:
    default: ""
  images_guardian_site_logo_url:
    default: ""
  images_guardian_site_logo_small_url:
    default: ""
  images_guardian_site_mobile_logo_url:
    default: ""
  images_guardian_site_favicon_url:
    default: ""
  images_guardian_site_logo_dark_url:
    default: ""
  images_guardian_site_logo_small_dark_url:
    default: ""
  images_guardian_site_mobile_logo_dark_url:
    default: ""